language: node_js
node_js:
  - "stable"
  - "lts/*"
sudo: false
services:
  - docker
  - mongodb
  - elasticsearch
# Per travis, to make sure ES and MongoDB are ready
before_script:
  - sleep 15
# whitelist
branches:
  only:
    - master
